"""Portable, local-first Agent Skills lifecycle for promin alpha.

Promin uses the open Agent Skills ``SKILL.md`` format as the portable semantic
source.  A small ``promin.skill.json`` sidecar owns Promin-specific capability,
security and provenance bindings.  Host-specific mirrors are generated by
``host_integration`` and never become an authority source.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import re
import shutil
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from .canonical import digest_value
from .platform_paths import resolved_temporary_directory
from .resources import bundle_root

_SKILL_NAME = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$")
_SEMVER = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")
_ALLOWED_HOSTS = {"generic", "codex", "claude", "cursor", "local"}
_ALLOWED_PLATFORMS = {"windows", "macos", "linux", "any"}
_ALLOWED_SCOPES = {"read-only", "workspace-write", "external-access"}
_MAX_SKILL_BYTES = 2 * 1024 * 1024
_MAX_SKILL_FILES = 128
_MAX_SKILL_MD_BYTES = 512 * 1024
_MAX_DOWNLOAD_BYTES = 4 * 1024 * 1024
_MAX_DESCRIPTION = 1024
_MAX_HOST_SKILLS = 256
_MAX_HOST_SKILL_SCAN_DEPTH = 4
_HOST_MARKERS = ("promin-generated-agent-skill-v4", "promin-generated-project-skill-wrapper-v1")
_BINDING_NAME = "promin.skill.json"
_SKILL_MD = "SKILL.md"


class SkillError(RuntimeError):
    pass


def _atomic_bytes(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(payload)
    os.replace(temporary, path)


def _atomic_json(path: Path, value: Mapping[str, Any]) -> None:
    payload = (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")
    _atomic_bytes(path, payload)


def _normalize_name(value: str) -> str:
    name = value.strip().casefold().replace("_", "-").replace(" ", "-")
    name = re.sub(r"-+", "-", name).strip("-")
    if not _SKILL_NAME.fullmatch(name) or "--" in name:
        raise SkillError("skill name must use lowercase letters, digits, and single hyphens")
    return name


def _parse_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    if path.is_symlink() or not path.is_file():
        raise SkillError(f"skill entry is not a regular file: {path}")
    size = path.stat().st_size
    if size < 8 or size > _MAX_SKILL_MD_BYTES:
        raise SkillError(f"SKILL.md size is outside the alpha bound: {path}")
    text = path.read_text(encoding="utf-8")
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = normalized.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SkillError(f"SKILL.md lacks YAML frontmatter: {path}")
    try:
        end = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration as exc:
        raise SkillError(f"SKILL.md frontmatter is not closed: {path}") from exc
    raw: dict[str, Any] = {}
    metadata: dict[str, str] = {}
    in_metadata = False
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            if in_metadata:
                item = line.strip()
                if ":" not in item:
                    raise SkillError(f"skill metadata entry is invalid: {path}")
                key, value = item.split(":", 1)
                metadata[key.strip()] = value.strip().strip('"\'')
                continue
            raise SkillError(f"nested frontmatter is unsupported outside metadata: {path}")
        if ":" not in line:
            raise SkillError(f"skill frontmatter entry is invalid: {path}")
        key, value = line.split(":", 1)
        key = key.strip()
        in_metadata = key == "metadata"
        if in_metadata:
            if value.strip() not in {"", "{}"}:
                raise SkillError(f"inline skill metadata is unsupported: {path}")
            continue
        raw[key] = value.strip().strip('"\'')
    if metadata:
        raw["metadata"] = metadata
    allowed = {"name", "description", "license", "compatibility", "metadata", "allowed-tools"}
    unknown = set(raw) - allowed
    if unknown:
        raise SkillError(f"unsupported SKILL.md frontmatter fields: {sorted(unknown)}")
    name = raw.get("name")
    description = raw.get("description")
    if not isinstance(name, str) or not _SKILL_NAME.fullmatch(name) or "--" in name:
        raise SkillError(f"skill name is invalid: {path}")
    if path.parent.name != name:
        raise SkillError(f"skill directory must match frontmatter name: {path}")
    if not isinstance(description, str) or not 1 <= len(description) <= _MAX_DESCRIPTION:
        raise SkillError(f"skill description is invalid: {path}")
    body = "\n".join(lines[end + 1 :]).strip() + "\n"
    if not body.strip():
        raise SkillError(f"skill body is empty: {path}")
    return raw, body


def _tree_receipt(root: Path) -> tuple[list[dict[str, Any]], int, str]:
    if root.is_symlink() or not root.is_dir():
        raise SkillError(f"skill root must be a real directory: {root}")
    files: list[dict[str, Any]] = []
    total = 0
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix().encode("utf-8")):
        if path.is_symlink():
            raise SkillError(f"skill package contains a symbolic link: {path}")
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if relative.startswith(".") and relative not in {_BINDING_NAME}:
            raise SkillError(f"hidden skill file is not allowed: {relative}")
        size = path.stat().st_size
        total += size
        files.append({
            "path": relative,
            "size_bytes": size,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        })
        if len(files) > _MAX_SKILL_FILES or total > _MAX_SKILL_BYTES:
            raise SkillError("skill package exceeds the alpha file or byte budget")
    if not any(item["path"] == _SKILL_MD for item in files):
        raise SkillError("skill package lacks SKILL.md")
    content_files = [item for item in files if item["path"] != _BINDING_NAME]
    content_digest = digest_value({"record_type": "AgentSkillContent", "files": content_files})
    return files, total, content_digest


def _default_binding(name: str, *, license_id: str, version: str = "0.1.0") -> dict[str, Any]:
    return {
        "record_type": "ProminSkillBinding",
        "skill_id": name,
        "version": version,
        "license": license_id,
        "capabilities": [f"skill.{name}"],
        "hosts": ["generic", "codex", "claude", "cursor", "local"],
        "platforms": ["windows", "macos", "linux"],
        "required_tools": [],
        "security_scope": "read-only",
        "enabled": True,
        "source_kind": "project-authored",
        "source_uri": None,
        "source_sha256": None,
        "content_digest": "0" * 64,
    }


def _load_binding(root: Path, frontmatter: Mapping[str, Any], content_digest: str) -> dict[str, Any]:
    path = root / _BINDING_NAME
    if not path.is_file() or path.is_symlink():
        raise SkillError(f"skill lacks {_BINDING_NAME}: {root}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SkillError(f"skill binding is invalid JSON: {root}") from exc
    required = {
        "record_type", "skill_id", "version", "license", "capabilities", "hosts",
        "platforms", "required_tools", "security_scope", "enabled", "source_kind",
        "source_uri", "source_sha256", "content_digest",
    }
    if not isinstance(value, dict) or set(value) != required:
        raise SkillError(f"skill binding fields are not exact: {root}")
    name = str(value.get("skill_id", ""))
    if value.get("record_type") != "ProminSkillBinding" or name != root.name or name != frontmatter.get("name"):
        raise SkillError(f"skill identities differ: {root}")
    version = value.get("version")
    if not isinstance(version, str) or not _SEMVER.fullmatch(version):
        raise SkillError(f"skill version is invalid: {root}")
    license_id = value.get("license")
    front_license = frontmatter.get("license")
    if not isinstance(license_id, str) or not license_id or (front_license and front_license != license_id):
        raise SkillError(f"skill license binding is invalid: {root}")
    for field, allowed, maximum in (
        ("hosts", _ALLOWED_HOSTS, 16),
        ("platforms", _ALLOWED_PLATFORMS, 8),
    ):
        items = value.get(field)
        if not isinstance(items, list) or not items or len(items) > maximum or any(not isinstance(item, str) for item in items) or not set(items) <= allowed:
            raise SkillError(f"skill {field} are invalid: {root}")
    capabilities = value.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities or len(capabilities) > 64 or any(not isinstance(item, str) or not item for item in capabilities):
        raise SkillError(f"skill capabilities are invalid: {root}")
    tools = value.get("required_tools")
    if not isinstance(tools, list) or len(tools) > 64 or any(not isinstance(item, str) or not item for item in tools):
        raise SkillError(f"skill required tools are invalid: {root}")
    if value.get("security_scope") not in _ALLOWED_SCOPES or not isinstance(value.get("enabled"), bool):
        raise SkillError(f"skill security binding is invalid: {root}")
    source_sha = value.get("source_sha256")
    if source_sha is not None and (not isinstance(source_sha, str) or re.fullmatch(r"[0-9a-f]{64}", source_sha) is None):
        raise SkillError(f"skill source digest is invalid: {root}")
    if value.get("content_digest") != content_digest:
        raise SkillError(f"skill content digest differs: {root}")
    identity = dict(value)
    identity["description"] = frontmatter["description"]
    identity["compatibility"] = frontmatter.get("compatibility")
    identity["allowed_tools"] = frontmatter.get("allowed-tools")
    identity["binding_digest"] = digest_value(value)
    identity["authority"] = False
    identity["pass_credit"] = False
    return identity


def validate_skill_directory(path: Path | str) -> dict[str, Any]:
    root = Path(path).resolve(strict=True)
    frontmatter, _body = _parse_frontmatter(root / _SKILL_MD)
    files, total, content_digest = _tree_receipt(root)
    binding = _load_binding(root, frontmatter, content_digest)
    return {
        **binding,
        "path": str(root),
        "file_count": len(files),
        "total_bytes": total,
        "files": files,
    }


def _skill_roots(project_root: Path) -> list[tuple[str, Path]]:
    return [
        ("bundled", bundle_root() / "skills"),
        ("project-portable", project_root / ".promin" / "portable" / "skills"),
        ("project-local", project_root / ".promin" / "skills"),
    ]


def _host_skill_roots(project_root: Path) -> list[tuple[str, Path]]:
    """Return native host catalogs without making them Promin authority.

    Project catalogs are checked before user catalogs.  The user locations are
    intentionally represented as local observations only and are never written
    into portable canonical state.
    """

    home = Path.home()
    return [
        ("project-codex", project_root / ".agents" / "skills"),
        ("project-claude", project_root / ".claude" / "skills"),
        ("project-cursor", project_root / ".cursor" / "skills"),
        ("user-codex", home / ".agents" / "skills"),
        ("user-claude", home / ".claude" / "skills"),
        ("user-cursor", home / ".cursor" / "skills"),
    ]


def _display_local_path(path: Path, project_root: Path) -> str:
    try:
        return path.relative_to(project_root).as_posix()
    except ValueError:
        try:
            return "~/" + path.relative_to(Path.home()).as_posix()
        except ValueError:
            return path.name


def _host_skill_metadata(path: Path, source: str, project_root: Path) -> dict[str, Any] | None:
    """Read only the bounded metadata needed for host-native skill discovery."""

    try:
        if path.is_symlink() or not path.is_file() or path.stat().st_size > _MAX_SKILL_MD_BYTES:
            return None
        raw = path.read_bytes()
    except OSError:
        return None
    text = raw.decode("utf-8", errors="replace").replace("\r\n", "\n").replace("\r", "\n")
    if any(marker in text for marker in _HOST_MARKERS):
        return None
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    try:
        end = next(index for index, line in enumerate(lines[1:160], start=1) if line.strip() == "---")
    except StopIteration:
        return None
    fields: dict[str, str] = {}
    for line in lines[1:end]:
        if line.startswith((" ", "\t")) or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        if key in {"name", "description", "license", "compatibility"}:
            fields[key] = value.strip().strip('"\'')
    raw_name = fields.get("name") or path.parent.name
    try:
        name = _normalize_name(raw_name)
    except SkillError:
        return None
    description = fields.get("description") or f"Host-provided skill {name}"
    description = description[:_MAX_DESCRIPTION]
    return {
        "record_type": "HostProvidedSkill",
        "skill_id": name,
        "description": description,
        "license": fields.get("license"),
        "compatibility": fields.get("compatibility"),
        "catalog_source": source,
        "path": _display_local_path(path.parent, project_root),
        "skill_md_sha256": hashlib.sha256(raw).hexdigest(),
        "managed_by_promin": False,
        "adoptable": source.startswith("project-"),
        "authority": False,
        "pass_credit": False,
    }


def discover_host_skills(project_root: Path | str) -> dict[str, Any]:
    """Discover existing Codex/Claude/Cursor skills as non-authoritative facts.

    The scan is bounded and metadata-only.  A host skill becomes a portable
    Promin skill only after an explicit ``skills install`` operation creates the
    digest/license/capability sidecar.
    """

    root = Path(project_root).resolve()
    found: list[dict[str, Any]] = []
    scanned = 0
    truncated = False
    for source, catalog in _host_skill_roots(root):
        if not catalog.is_dir() or catalog.is_symlink():
            continue
        catalog_depth = len(catalog.parts)
        for directory, dirnames, filenames in os.walk(catalog, followlinks=False):
            current = Path(directory)
            depth = len(current.parts) - catalog_depth
            dirnames[:] = sorted(
                name for name in dirnames
                if depth < _MAX_HOST_SKILL_SCAN_DEPTH
                and not (current / name).is_symlink()
                and not name.startswith(".")
            )
            if _SKILL_MD not in filenames:
                continue
            scanned += 1
            if scanned > _MAX_HOST_SKILLS:
                truncated = True
                break
            metadata = _host_skill_metadata(current / _SKILL_MD, source, root)
            if metadata is not None:
                found.append(metadata)
        if truncated:
            break
    found.sort(key=lambda item: (str(item["skill_id"]), str(item["catalog_source"]), str(item["path"])))
    by_id: dict[str, set[str]] = {}
    for item in found:
        by_id.setdefault(str(item["skill_id"]), set()).add(str(item["skill_md_sha256"]))
    conflicts = sorted(skill_id for skill_id, digests in by_id.items() if len(digests) > 1)
    return {
        "record_type": "HostSkillDiscovery",
        "status": "truncated" if truncated else "ready",
        "skills": found,
        "skill_count": len(found),
        "conflicting_skill_ids": conflicts,
        "scan_limit": _MAX_HOST_SKILLS,
        "metadata_only": True,
        "authority": False,
        "pass_credit": False,
    }


def discover_skills(project_root: Path | str) -> list[dict[str, Any]]:
    root = Path(project_root).resolve()
    found: dict[str, dict[str, Any]] = {}
    for source, directory in _skill_roots(root):
        if not directory.is_dir() or directory.is_symlink():
            continue
        for child in sorted(directory.iterdir(), key=lambda item: item.name.casefold()):
            if not child.is_dir() or child.is_symlink() or not (child / _SKILL_MD).is_file():
                continue
            value = validate_skill_directory(child)
            if not value["enabled"]:
                continue
            value["catalog_source"] = source
            existing = found.get(value["skill_id"])
            if existing and existing["content_digest"] != value["content_digest"]:
                raise SkillError(f"conflicting enabled skills share one ID: {value['skill_id']}")
            found[value["skill_id"]] = value
    return [found[key] for key in sorted(found)]


def skill_catalog(project_root: Path | str) -> dict[str, Any]:
    skills = discover_skills(project_root)
    host = discover_host_skills(project_root)
    metadata_chars = sum(len(item["skill_id"]) + len(item["description"]) for item in skills)
    metadata_chars += sum(len(item["skill_id"]) + len(item["description"]) for item in host["skills"])
    managed_ids = {str(item["skill_id"]) for item in skills}
    host_skills = [
        {**item, "shadowed_by_managed_skill": str(item["skill_id"]) in managed_ids}
        for item in host["skills"]
    ]
    return {
        "record_type": "SkillCatalog",
        "status": "degraded" if host["conflicting_skill_ids"] else "ready",
        "skill_count": len(skills),
        "host_skill_count": len(host_skills),
        "metadata_character_estimate": metadata_chars,
        "metadata_token_estimate": max(0, (metadata_chars + 3) // 4),
        "skills": [
            {
                key: item.get(key)
                for key in (
                    "skill_id", "version", "description", "license", "capabilities",
                    "hosts", "platforms", "required_tools", "security_scope",
                    "content_digest", "binding_digest", "catalog_source", "total_bytes",
                )
            }
            for item in skills
        ],
        "host_skills": host_skills,
        "host_conflicting_skill_ids": host["conflicting_skill_ids"],
        "host_scan_truncated": host["status"] == "truncated",
        "adoption_policy": "Host skills are usable by their host but become Promin-managed only after explicit hash/license-bound installation.",
        "authority": False,
        "pass_credit": False,
    }


def _skill_md(name: str, description: str, license_id: str, body: str) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        f"license: {license_id}\n"
        "metadata:\n"
        "  promin-format: open-agent-skills\n"
        "---\n\n"
        f"{body.strip()}\n"
    )


def create_skill(
    project_root: Path | str,
    *,
    name: str,
    description: str,
    body: str,
    version: str = "0.1.0",
    license_id: str = "Apache-2.0",
    capabilities: Sequence[str] = (),
    hosts: Sequence[str] = ("generic", "codex", "claude", "cursor", "local"),
    platforms: Sequence[str] = ("windows", "macos", "linux"),
    required_tools: Sequence[str] = (),
    security_scope: str = "read-only",
    portable: bool = True,
) -> dict[str, Any]:
    root = Path(project_root).resolve()
    skill_id = _normalize_name(name)
    if not isinstance(description, str) or not 1 <= len(description.strip()) <= _MAX_DESCRIPTION:
        raise SkillError("skill description must be 1-1024 characters")
    if not isinstance(body, str) or not body.strip():
        raise SkillError("skill instructions must be non-empty")
    if not _SEMVER.fullmatch(version):
        raise SkillError("skill version must be SemVer")
    if security_scope not in _ALLOWED_SCOPES:
        raise SkillError("skill security scope is invalid")
    destination_root = root / ".promin" / ("portable/skills" if portable else "skills")
    destination = destination_root / skill_id
    if destination.exists() or destination.is_symlink():
        raise SkillError(f"skill already exists: {skill_id}")
    destination.mkdir(parents=True)
    try:
        _atomic_bytes(destination / _SKILL_MD, _skill_md(skill_id, description.strip(), license_id, body).encode("utf-8"))
        binding = _default_binding(skill_id, license_id=license_id, version=version)
        binding.update({
            "capabilities": list(capabilities) or [f"skill.{skill_id}"],
            "hosts": list(hosts),
            "platforms": list(platforms),
            "required_tools": list(required_tools),
            "security_scope": security_scope,
            "source_kind": "project-authored" if portable else "project-local",
        })
        _atomic_json(destination / _BINDING_NAME, binding)
        _files, _total, content_digest = _tree_receipt(destination)
        binding["content_digest"] = content_digest
        _atomic_json(destination / _BINDING_NAME, binding)
        validated = validate_skill_directory(destination)
    except BaseException:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    return {
        "record_type": "SkillCreationResult",
        "status": "created",
        "portable": portable,
        "skill": validated,
        "sync_command": "promin skills sync",
        "authority": False,
        "pass_credit": False,
    }


def request_skill(project_root: Path | str, *, requirement: str) -> dict[str, Any]:
    root = Path(project_root).resolve()
    normalized = requirement.strip()
    if not normalized or len(normalized) > 2048:
        raise SkillError("skill requirement must be 1-2048 characters")
    catalog = skill_catalog(root)
    terms = {item.casefold() for item in re.findall(r"[A-Za-z0-9_.+-]+", normalized)}
    matches = []
    for skill in catalog["skills"]:
        haystack = " ".join([skill["skill_id"], skill["description"], *skill["capabilities"]]).casefold()
        score = sum(1 for term in terms if term in haystack)
        if score:
            matches.append({"skill_id": skill["skill_id"], "score": score, "description": skill["description"], "kind": "promin-managed"})
    for skill in catalog.get("host_skills", []):
        haystack = " ".join([str(skill.get("skill_id", "")), str(skill.get("description", ""))]).casefold()
        score = sum(1 for term in terms if term in haystack)
        if score:
            matches.append({
                "skill_id": skill["skill_id"], "score": score,
                "description": skill["description"], "kind": "host-provided-unmanaged",
                "path": skill.get("path"), "adoptable": skill.get("adoptable", False),
            })
    matches.sort(key=lambda item: (-item["score"], item["skill_id"], item["kind"]))
    identity = {
        "record_type": "SkillRequest",
        "requirement": normalized,
        "matching_installed_skills": matches[:8],
        "resolution_order": [
            "reuse-compatible-installed-skill",
            "create-project-skill",
            "install-explicit-hash-pinned-skill",
        ],
        "network_download_requires_explicit_opt_in": True,
        "authority": False,
        "pass_credit": False,
    }
    request_id = digest_value(identity)
    record = {**identity, "request_id": request_id}
    path = root / ".promin" / "generated" / "skill-requests" / f"{request_id[:24]}.json"
    _atomic_json(path, record)
    return {
        **record,
        "status": "matched" if matches else "creation-or-install-required",
        "create_command": "promin skills create <name> --description <text> --instructions-file <path>",
        "install_command": "promin skills install <path-or-https-url> --sha256 <digest>",
        "adopt_existing_command": "promin skills install .agents/skills/<name> --license <SPDX>",
    }


def _safe_extract_zip(payload: bytes, destination: Path) -> None:
    try:
        archive = zipfile.ZipFile(io.BytesIO(payload))
    except zipfile.BadZipFile as exc:
        raise SkillError("skill archive is not a valid ZIP") from exc
    total = 0
    names: set[str] = set()
    for info in archive.infolist():
        name = info.filename.replace("\\", "/")
        if not name or name.endswith("/"):
            continue
        path = Path(name)
        if path.is_absolute() or ".." in path.parts or ":" in name or name.startswith("/"):
            raise SkillError("skill archive contains an unsafe path")
        folded = name.casefold()
        if folded in names:
            raise SkillError("skill archive contains a casefold path collision")
        names.add(folded)
        mode = (info.external_attr >> 16) & 0o170000
        if mode == 0o120000:
            raise SkillError("skill archive contains a symbolic link")
        total += info.file_size
        if len(names) > _MAX_SKILL_FILES or total > _MAX_SKILL_BYTES:
            raise SkillError("skill archive exceeds the alpha budget")
    archive.extractall(destination)


def _locate_skill_root(extracted: Path) -> Path:
    if (extracted / _SKILL_MD).is_file():
        return extracted
    candidates = [path.parent for path in extracted.rglob(_SKILL_MD) if path.is_file() and not path.is_symlink()]
    unique = sorted(set(candidates), key=lambda item: item.as_posix())
    if len(unique) != 1:
        raise SkillError("skill source must contain exactly one SKILL.md root")
    return unique[0]


def _standalone_skill_name(payload: bytes) -> str:
    if len(payload) > _MAX_SKILL_MD_BYTES:
        raise SkillError("standalone SKILL.md exceeds the alpha bound")
    try:
        text = payload.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")
    except UnicodeDecodeError as exc:
        raise SkillError("standalone SKILL.md is not UTF-8") from exc
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SkillError("standalone SKILL.md lacks frontmatter")
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line.startswith("name:"):
            return _normalize_name(line.split(":", 1)[1].strip().strip("\"'"))
    raise SkillError("standalone SKILL.md lacks a name")


def _source_tree_digest(root: Path) -> str:
    files: list[dict[str, Any]] = []
    total = 0
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix().encode("utf-8")):
        if path.is_symlink():
            raise SkillError("local skill source contains a symbolic link")
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        size = path.stat().st_size
        total += size
        files.append({"path": relative, "size_bytes": size, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        if len(files) > _MAX_SKILL_FILES or total > _MAX_SKILL_BYTES:
            raise SkillError("local skill source exceeds the alpha budget")
    if not files:
        raise SkillError("local skill source is empty")
    return digest_value({"record_type": "SkillSourceTree", "files": files})


def _read_source(source: str, *, allow_network: bool, expected_sha256: str | None) -> tuple[bytes | None, Path | None, str, str]:
    parsed = urllib.parse.urlparse(source)
    if parsed.scheme in {"http", "https"}:
        if not allow_network:
            raise SkillError("remote skill installation requires --allow-network")
        if parsed.scheme != "https":
            raise SkillError("remote skill source must use HTTPS")
        if not expected_sha256 or re.fullmatch(r"[0-9a-f]{64}", expected_sha256) is None:
            raise SkillError("remote skill installation requires an exact SHA-256")
        request = urllib.request.Request(source, headers={"User-Agent": "promin-skill-installer/1"})
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                payload = response.read(_MAX_DOWNLOAD_BYTES + 1)
        except Exception as exc:
            raise SkillError(f"cannot download skill source: {type(exc).__name__}") from exc
        if len(payload) > _MAX_DOWNLOAD_BYTES:
            raise SkillError("remote skill source exceeds the download budget")
        digest = hashlib.sha256(payload).hexdigest()
        if digest != expected_sha256:
            raise SkillError("remote skill source digest differs")
        return payload, None, "remote-https", digest
    path = Path(source).expanduser().resolve(strict=True)
    if path.is_symlink():
        raise SkillError("local skill source symlink rejected")
    if path.is_dir():
        digest = _source_tree_digest(path)
        if expected_sha256 and digest != expected_sha256:
            raise SkillError("local skill source digest differs")
        return None, path, "local-directory", digest
    if not path.is_file() or path.stat().st_size > _MAX_DOWNLOAD_BYTES:
        raise SkillError("local skill source is not a bounded regular file")
    payload = path.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if expected_sha256 and digest != expected_sha256:
        raise SkillError("local skill source digest differs")
    return payload, None, "local-file", digest


def install_skill(
    project_root: Path | str,
    *,
    source: str,
    expected_sha256: str | None = None,
    allow_network: bool = False,
    portable: bool = True,
    expected_license: str | None = None,
) -> dict[str, Any]:
    root = Path(project_root).resolve()
    payload, directory, source_kind, source_digest = _read_source(
        source, allow_network=allow_network, expected_sha256=expected_sha256
    )
    with resolved_temporary_directory(prefix="promin-skill-") as staging:
        if directory is not None:
            source_root = _locate_skill_root(directory)
            candidate = staging / source_root.name
            shutil.copytree(source_root, candidate, symlinks=False)
        elif source.casefold().endswith("skill.md") and payload is not None:
            candidate = staging / _standalone_skill_name(payload)
            candidate.mkdir()
            (candidate / _SKILL_MD).write_bytes(payload)
        else:
            _safe_extract_zip(payload or b"", staging)
            candidate = _locate_skill_root(staging)
        frontmatter, _body = _parse_frontmatter(candidate / _SKILL_MD)
        skill_id = _normalize_name(str(frontmatter["name"]))
        if candidate.name != skill_id:
            renamed = staging / skill_id
            if renamed.exists():
                raise SkillError("skill archive root name conflicts")
            candidate.rename(renamed)
            candidate = renamed
        license_id = str(frontmatter.get("license") or expected_license or "")
        if not license_id:
            raise SkillError("installed skill must declare a license")
        if expected_license and license_id != expected_license:
            raise SkillError("installed skill license differs from the expected license")
        binding_path = candidate / _BINDING_NAME
        if binding_path.is_file():
            binding = json.loads(binding_path.read_text(encoding="utf-8"))
        else:
            binding = _default_binding(skill_id, license_id=license_id)
        binding.update({
            "skill_id": skill_id,
            "license": license_id,
            "source_kind": source_kind,
            "source_uri": source if source_kind == "remote-https" else None,
            "source_sha256": source_digest if re.fullmatch(r"[0-9a-f]{64}", source_digest) else None,
            "content_digest": "0" * 64,
        })
        _atomic_json(binding_path, binding)
        _files, _total, content_digest = _tree_receipt(candidate)
        if source_kind == "local-directory":
            source_digest = content_digest
            binding["source_sha256"] = source_digest
        binding["content_digest"] = content_digest
        _atomic_json(binding_path, binding)
        validate_skill_directory(candidate)
        destination_root = root / ".promin" / ("portable/skills" if portable else "skills")
        destination = destination_root / skill_id
        if destination.exists() or destination.is_symlink():
            raise SkillError(f"skill already exists: {skill_id}")
        destination_root.mkdir(parents=True, exist_ok=True)
        temporary_destination = destination_root / f".{skill_id}.tmp"
        shutil.rmtree(temporary_destination, ignore_errors=True)
        shutil.copytree(candidate, temporary_destination, symlinks=False)
        os.replace(temporary_destination, destination)
    return {
        "record_type": "SkillInstallationResult",
        "status": "installed",
        "source_kind": source_kind,
        "source_sha256": source_digest,
        "portable": portable,
        "skill": validate_skill_directory(destination),
        "sync_command": "promin skills sync",
        "authority": False,
        "pass_credit": False,
    }


def remove_skill(project_root: Path | str, *, name: str, portable: bool = True) -> dict[str, Any]:
    root = Path(project_root).resolve()
    skill_id = _normalize_name(name)
    path = root / ".promin" / ("portable/skills" if portable else "skills") / skill_id
    if not path.is_dir() or path.is_symlink():
        raise SkillError(f"skill is not installed: {skill_id}")
    receipt = validate_skill_directory(path)
    shutil.rmtree(path)
    return {
        "record_type": "SkillRemovalResult",
        "status": "removed",
        "skill_id": skill_id,
        "content_digest": receipt["content_digest"],
        "authority": False,
        "pass_credit": False,
    }


# Compatibility alias retained only inside the current alpha source tree. The
# public model is the open Agent Skills directory contract above.
validate_skill = validate_skill_directory
